blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/your-username/nodetsp/discussions
    about: Ask questions, share ideas, or start discussions about NodeTSP
  - name: 📚 Documentation
    url: https://github.com/your-username/nodetsp#readme
    about: Check the README for usage information
